# Teleop configuration for PS4 joystick using the x-pad configuration.
teleop_twist_joy:
  axis_linear:
    x: 1
    y: 0
  scale_linear:
    x: 0.4
    y: 0.4
  scale_linear_turbo:
    x: 0.4
    y: 0.4
  axis_angular:
    yaw: 3
  scale_angular:
    yaw: 0.5
  scale_angular_turbo:
    yaw: 0.5
  enable_button: 4
  enable_turbo_button: 5
joy_node:
  deadzone: 0.1
  autorepeat_rate: 20
